### ISSUE TITLE
Inline snapshots TODO

### ISSUE THREAD

**Issue by aaronabramov** [aaronabramov/k9#45]
- [x] Transaction support for file writes (concurrently updated source files, updating multiple snapshots in the same file while its source is changisg)
- [ ] properly escape all characters that can mess up string literals (`"#`)
- [ ] Remove all `.unwrap()` and `.expect()` and replace with Result with nice error messages and error chains
- [x] Write a good test suite that create a temporary projects and runs/updates snapshots in it
- [x] reformat source file (rustfmt) after updating an inline snapshot in it
- [ ] adjust inline snapshot failure message to not include inline snapshot literal twice
- [ ] `k9::assert_matches_inline_snapshot` fails to locate macro location
